const CGPA_Data = {
  EL: {
    S1: [
      {code: "1001",subject: "English for Communication I",type: "F",credit: 3},
      {code: "1002",subject: "Engineering Mathematics I",type: "F",credit: 6},
      {code: "1003",subject: "Engineering Physics I",type: "F",credit: 3},
      {code: "1004",subject: "Engineering Chemistry I",type: "F",credit: 3},
      {code: "1009",subject: "Health & Physical Education",type: "C",credit: 2},
      {code: "1008",subject: "Computing Fundamentals",type: "C",credit: 4},
    ],
    S2: [
      {code: "2001",subject: "English for Communication II",type: "F",credit: 3},
      {code: "2002",subject: "Engineering Mathematics II",type: "F",credit: 6},
      {code: "2003",subject: "Engineering Physics II",type: "F",credit: 3},
      {code: "2004",subject: "Engineering Chemistry II",type: "F",credit: 3},
      {code: "2041",subject: "Basic Electronics",type: "B",credit: 4},
      {code: "2005",subject: "Engineering Graphics",type: "F",credit: 5},
      {code: "2008",subject: "Workshop Practice",type: "F",credit: 3},
      {code: "2007",subject: "Engineering Science Lab II",type: "F",credit: 3},
      {code: "2049",subject: "Basic Electronics Lab",type: "B",credit: 2},
      {code: "2009",subject: "Life Skill",type: "C",credit: 2},
    ],
    S3: [
      {code: "3043",subject: "Electrical Technology",type: "B",credit: 4},
      {code: "3044",subject: "Electronic Devices & Circuits",type: "B",credit: 5},
      {code: "3042",subject: "Digital Electronics",type: "B",credit: 4},
      {code: "3041",subject: "Communication Engineering",type: "B",credit: 4},
      {code: "3001",subject: "Environmental Science & Disaster Management",type: "C",credit: 3},
      {code: "3047",subject: "Electronics Circuits Lab",type: "B",credit: 3},
      {code: "3048",subject: "Digital Electronics Lab",type: "B",credit: 3},
      {code: "3049",subject: "Analogue Communication Lab",type: "B",credit: 3},
    ],
    S4: [
      {code: "4042",subject: "Linear Integrated Circuits",type: "B",credit: 4},
      {code: "4041",subject: "Electronics Instruments & Measurements",type: "A",credit: 4},
      {code: "4043",subject: "Microcontroller and Interfacing",type: "A",credit: 5},
      {code: "4044",subject: "Programming in C",type: "B",credit: 4},
      {code: "4047",subject: "Linear Integrated Circuits Lab",type: "A",credit: 3},
      {code: "4048",subject: "Microcontroller & Interfacing Lab",type: "A",credit: 3},
      {code: "4049",subject: "Programming in C Lab",type: "B",credit: 3},
      {code: "4009",subject: "Mini Project",type: "A",credit: 5},
    ],
    S5: [
      {code: "5001",subject: "Industrial Management & Safety",type: "C",credit: 4},
      {code: "5041",subject: "Embedded System",type: "A",credit: 4},
      {code: "5042",subject: "Industrial Electronics & PLC",type: "A",credit: 4},
      {code: "504x",subject: "S5 Elective Subject",type: "E",credit: 4},
      {code: "5049",subject: "Embedded System Lab",type: "A",credit: 2},
      {code: "5048",subject: "Industrial Electronics & PLC Lab",type: "A",credit: 2},
      {code: "5047",subject: "PCB & Spice Lab",type: "A",credit: 3},
      {code: "5009",subject: "Industrial Training/Industrial Visit/Collaborative work",type: "A",credit: 2},
    ],
    S6: [
      {code: "6042",subject: "Communication Systems",type: "A",credit: 5},
      {code: "6043",subject: "Computer Hardware & Networking",type: "A",credit: 5},
      {code: "6041",subject: "Advanced Microprocessors",type: "A",credit: 5},
      {code: "604x",subject: "S6 Elective Subject",type: "E",credit: 4},
      {code: "6049",subject: "Computer Hardware and Networking Lab",type: "A",credit: 3},
      {code: "6048",subject: "HDL and Simulation Software Lab",type: "A",credit: 3},
      {code: "6009",subject: "Project & Seminar",type: "A",credit: 10},
    ],
  }
};

